package com.tu.entity;
// Generated Oct 25, 2018 2:31:40 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domain generated by hbm2java
 */
@Entity
@Table(name = "domain")
public class Domain implements java.io.Serializable {

	private int domainId;
	private String name;
	private Set<User> users = new HashSet<User>(0);
	private Set<Team> teams = new HashSet<Team>(0);

	public Domain() {
	}

	public Domain(int domainId, String name) {
		this.domainId = domainId;
		this.name = name;
	}

	public Domain(int domainId, String name, Set<User> users, Set<Team> teams) {
		this.domainId = domainId;
		this.name = name;
		this.users = users;
		this.teams = teams;
	}

	@Id

	@Column(name = "domain_id", unique = true, nullable = false)
	public int getDomainId() {
		return this.domainId;
	}

	public void setDomainId(int domainId) {
		this.domainId = domainId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domain")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domain")
	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

}
