package com.tu.entity;
// Generated Oct 25, 2018 2:31:40 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team")
public class Team implements java.io.Serializable {

	private int teamId;
	private Domain domain;
	private Region region;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Team() {
	}

	public Team(int teamId, Domain domain, Region region, String name) {
		this.teamId = teamId;
		this.domain = domain;
		this.region = region;
		this.name = name;
	}

	public Team(int teamId, Domain domain, Region region, String name, Set<User> users) {
		this.teamId = teamId;
		this.domain = domain;
		this.region = region;
		this.name = name;
		this.users = users;
	}

	@Id

	@Column(name = "team_id", unique = true, nullable = false)
	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "domain_id", nullable = false)
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region_id", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "team")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
