package com.tu.entity;
// Generated Oct 25, 2018 2:31:40 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Technology generated by hbm2java
 */
@Entity
@Table(name = "technology")
public class Technology implements java.io.Serializable {

	private int techId;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Technology() {
	}

	public Technology(int techId, String name) {
		this.techId = techId;
		this.name = name;
	}

	public Technology(int techId, String name, Set<User> users) {
		this.techId = techId;
		this.name = name;
		this.users = users;
	}

	@Id

	@Column(name = "tech_id", unique = true, nullable = false)
	public int getTechId() {
		return this.techId;
	}

	public void setTechId(int techId) {
		this.techId = techId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "technology")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
