// { autofold
  
package com.tu.entity;
// Generated Oct 25, 2018 2:31:40 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedSubgraph;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */

// }
@Entity
@Table(name = "user")
@NamedEntityGraph(name = "user-with-team", 
		attributeNodes = @NamedAttributeNode(value = "team", subgraph = "region"), 
			subgraphs = @NamedSubgraph(name = "region", attributeNodes = @NamedAttributeNode("region")))
public class User implements java.io.Serializable {

	private int userId;
	private Domain domain;
	private Region region;
	private Team team;
	private Technology technology;
	private String name;
	private String username;
	private Boolean isadmin;

	// { autofold
	  
	public User() {
	}

	public User(int userId, Domain domain, Region region, Team team, Technology technology) {
		this.userId = userId;
		this.domain = domain;
		this.region = region;
		this.team = team;
		this.technology = technology;
	}

	public User(int userId, Domain domain, Region region, Team team, Technology technology, String name,
			String username, Boolean isadmin) {
		this.userId = userId;
		this.domain = domain;
		this.region = region;
		this.team = team;
		this.technology = technology;
		this.name = name;
		this.username = username;
		this.isadmin = isadmin;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	// }

	@ManyToOne(fetch = FetchType.EAGER ,cascade = CascadeType.ALL)
	@JoinColumn(name = "domain_id", nullable = false)
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "region_id", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	// { autofold
	  
	public void setRegion(Region region) {
		this.region = region;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "team_id", nullable = false)
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "tech_id", nullable = false)
	public Technology getTechnology() {
		return this.technology;
	}

	public void setTechnology(Technology technology) {
		this.technology = technology;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "isadmin")
	public Boolean getIsadmin() {
		return this.isadmin;
	}

	public void setIsadmin(Boolean isadmin) {
		this.isadmin = isadmin;
	}
	
	// }

}
